FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y \
    sudo 

RUN sudo apt install openjdk-17-jdk -y
RUN sudo apt install openjdk-17-jre -y
RUN sudo apt-get install jetty9 -y
RUN sudo apt-get install redis-server -y

WORKDIR /home

COPY GeoServer /home/geoserver
COPY GeoMesa-Gateway/target/GeoMesaGateway-v0.2.3.jar /home/gateway/geomesa-gateway.jar
COPY GeoMesa-Gateway/target/classes/application.properties /home/gateway/application.properties

EXPOSE 6379 8000 8080

COPY start_services.sh /home/start_services.sh
RUN chmod +x /home/start_services.sh

# Avvia i servizi nello script
CMD ["/home/start_services.sh"]
